version: "3.8"

services:
  backend:
    build: .
    container_name: ms3-backend
    env_file: .env
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5003

  neo4j:
    image: neo4j:5.14
    container_name: ms3-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "neo4j-admin ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      NEO4J_AUTH: "${NEO4J_AUTH}"
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_tls__level: "DISABLED"
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"

volumes:
  neo4j_data:
