version: "3.8"

services:
  backend:
    container_name: ms3-backend
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - neo4j
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  neo4j:
    image: neo4j:5.14
    container_name: ms3-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: "${NEO4J_AUTH}"
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_bolt_tls__level: "DISABLED"
      NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"

volumes:
  neo4j_data:
